---
version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-web
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
networks:
  default:
    external:
      name: proxy-network
volumes:
  jenkins-data:
